
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR';
export const INCREMENT_QUESTION_INDEX = 'INCREMENT_QUESTION_INDEX';
export const DECREMENT_QUESTION_INDEX = 'DECREMENT_QUESTION_INDEX';
export const DEFAULT_LOCALE = 'en';